services:
  - type: web
    name: tunzymd
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    healthCheckPath: /ping
    envVars:
      - key: OWNER_NUMBER
        value: 27688259160
      - key: APP_URL
        value: https://spiderweb.onrender.com
      - key: PORT
        value: 3000 
